# Generated by Django 6.0.3 on 2026-04-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ['-checked_at'], 'verbose_name_plural': 'Wpisy usług'},
        ),
        migrations.AlterModelOptions(
            name='monitoredservice',
            options={'verbose_name_plural': 'Usługi do monitorowania'},
        ),
        migrations.AddField(
            model_name='monitoredservice',
            name='timeout_ms',
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='monitoredservice',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='checked_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='status',
            field=models.CharField(choices=[('ok', 'OK'), ('fail', 'Fail'), ('timeout', 'Timeout')], db_index=True, max_length=10),
        ),
    ]
