# Generated by Django 6.0.3 on 2026-04-25 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_remove_monitoredservice_api_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoredservice',
            name='name',
        ),
    ]
