# Generated by Django 6.0.3 on 2026-04-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_remove_monitoredservice_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoredservice',
            name='url',
        ),
    ]
