# Generated by Django 6.0.3 on 2026-04-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_remove_monitoredservice_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='response_time_ms',
            new_name='execute_time_ms',
        ),
    ]
