# Generated by Django 6.0.3 on 2026-04-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_rename_response_time_ms_logentry_execute_time_ms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
