# Generated by Django 6.0.3 on 2026-04-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_alter_logentry_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='execute_time_ms',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='status',
        ),
        migrations.AlterField(
            model_name='logentry',
            name='message',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='status_code',
            field=models.IntegerField(blank=True, choices=[(0, 'ok'), (1, 'warning'), (2, 'critical'), (100, 'app_specyfic')], default=None, null=True),
        ),
    ]
