# Generated by Django 6.0.3 on 2026-04-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_remove_logentry_execute_time_ms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='status_code',
            field=models.IntegerField(blank=True, choices=[(0, 'ok'), (1, 'warning'), (2, 'critical'), (100, 'app_specyfic')], default=0, null=True),
        ),
    ]
