# Generated by Django 6.0.3 on 2026-04-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_alter_logentry_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredservice',
            name='last_check_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitoredservice',
            name='last_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
