# Generated by Django 6.0.3 on 2026-04-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_monitoredservice_last_check_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredservice',
            name='last_change_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
