# Generated by Django 6.0.3 on 2026-09-26 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_monitoredservice_last_change_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredservice',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Opis (np. Backup telefonu Pixel)'),
        ),
        migrations.AddField(
            model_name='monitoredservice',
            name='service_name',
            field=models.CharField(default='backup', max_length=64, verbose_name='Identyfikator usługi (np. backup, temperatura, vps_cron)'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='status_code',
            field=models.IntegerField(blank=True, choices=[(0, 'ok'), (1, 'warning'), (2, 'critical'), (100, 'app_specific')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='monitoredservice',
            name='timeout_ms',
            field=models.IntegerField(default=5000, help_text='Bazowy timeout w milisekundach'),
        ),
        migrations.AlterField(
            model_name='monitoredservice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='monitoredservice',
            unique_together={('user', 'service_name')},
        ),
    ]
