# Generated by Django 6.0.3 on 2026-09-26 12:56

import django.db.models.deletion
import monitoring.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_monitoredservice_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ['-checked_at'], 'verbose_name': 'Wpis logu usługi', 'verbose_name_plural': 'Wpisy logów usług'},
        ),
        migrations.AlterModelOptions(
            name='monitoredservice',
            options={'verbose_name': 'Usługa monitoringu (Service Account)', 'verbose_name_plural': 'Usługi monitoringu (Service Accounts)'},
        ),
        migrations.AddField(
            model_name='monitoredservice',
            name='service_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_profile', to=settings.AUTH_USER_MODEL, verbose_name='Konto techniczne maszyny (DRF User)'),
        ),
        migrations.AlterField(
            model_name='monitoredservice',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Opis (np. Telefon Pixel Maćka)'),
        ),
        migrations.AlterField(
            model_name='monitoredservice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Czy usługa aktywna'),
        ),
        migrations.AlterField(
            model_name='monitoredservice',
            name='last_change_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ostatnia zmiana statusu'),
        ),
        migrations.AlterField(
            model_name='monitoredservice',
            name='last_check_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ostatnie sprawdzenie'),
        ),
        migrations.AlterField(
            model_name='monitoredservice',
            name='last_status',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ostatni kod statusu'),
        ),
        migrations.AlterField(
            model_name='monitoredservice',
            name='service_name',
            field=models.CharField(max_length=64, verbose_name='Identyfikator usługi (np. backup, temperatura, vps_cron)'),
        ),
        migrations.AlterField(
            model_name='monitoredservice',
            name='user',
            field=models.ForeignKey(default=monitoring.models.get_default_owner, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_services', to=settings.AUTH_USER_MODEL, verbose_name='Opiekun (użytkownik nadrzędny)'),
        ),
    ]
