# Generated by Django 6.0.3 on 2026-09-26 13:36

import django.db.models.deletion
import monitoring.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_alter_logentry_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoredservice',
            name='service_user',
            field=models.OneToOneField(default=monitoring.models.get_default_owner, on_delete=django.db.models.deletion.CASCADE, related_name='service_profile', to=settings.AUTH_USER_MODEL, verbose_name='Konto techniczne maszyny (DRF User)'),
        ),
    ]
