+ /DCIM/**
+ /Pictures/**
+ /Documents/**
+ /Download/**
+ /Music/**
+ /Android/media/**
- **.tmp
- **.swp
- **.bak
- **.nomedia
- **.thumbnails/**
- **Cache/**
- **cache/**
- **Thumbs.db
- **.DS_Store
- *

