#!/data/data/com.termux/files/usr/bin/bash
# ==============================================================================
# Termux -> Raspberry Pi Backup Config
# VERSION: 2026-03-12 21:00
# ==============================================================================

# ==============================
# 1. KONFIGURACJA MINIMALNA
# ==============================

TOKEN="TU_WSTAW_TOKEN"
KTO="Maciek"
RUN_HOUR="21"

# ==============================
# 2. KONFIGURACJE POZOSTAŁA
# ==============================
PI_USER="pi"
PI_HOST="192.168.5.148"
SERVER="https://192.168.5.148:8000"
DEST_BASE="/media/pi/elemele"
RSYNC_DEST_PREFIX="pi:"

RSYNC_BIN="/data/data/com.termux/files/usr/bin/rsync"
SSH_BIN="/data/data/com.termux/files/usr/bin/ssh"

ROOT_PATH="/storage/emulated/0"
SOURCE_DIR="$SCRIPT_DIR/backup"
LOG_DIR="$SCRIPT_DIR/backup_logs"
LOG_FILE="$LOG_DIR/backup.log"

EXCLUDE_PATTERNS=('*~' '*.tmp' '*.swp' '*.bak' '.DS_Store' 'Thumbs.db' '*.nomedia')

