# Generated by Django 6.0.3 on 2026-03-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backupapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupGlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_panel_active', models.BooleanField(default=False, verbose_name='Panel aktywny')),
                ('active_until', models.DateTimeField(blank=True, null=True, verbose_name='Aktywny do')),
            ],
            options={
                'verbose_name': 'Ustawienia Globalne',
                'verbose_name_plural': 'Ustawienia Globalne',
            },
        ),
    ]
