# Generated by Django 6.0.3 on 2026-09-23 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backupapp', '0003_backupagent_delete_backupglobalsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backupagent',
            options={'verbose_name': 'Agent backupu', 'verbose_name_plural': 'Agenci backupu'},
        ),
        migrations.AlterModelOptions(
            name='backupinvitation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Zaproszenie do backupu', 'verbose_name_plural': 'Zaproszenia do backupu'},
        ),
        migrations.AddField(
            model_name='backupagent',
            name='last_status_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='backupagent',
            name='log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='backupagent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backup_agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='backupinvitation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
