# Generated by Django 6.0.3 on 2026-09-23 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backupapp', '0004_alter_backupagent_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backupinvitation',
            options={'ordering': ['user__username'], 'verbose_name': 'Zaproszenie / instalacja telefonu', 'verbose_name_plural': 'Zaproszenia / instalacje telefonów'},
        ),
        migrations.AlterField(
            model_name='backupinvitation',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Czy użyty / skonfigurowany'),
        ),
        migrations.AlterField(
            model_name='backupinvitation',
            name='token_link',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='Token autoryzacyjny'),
        ),
        migrations.AlterField(
            model_name='backupinvitation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backup_invitation', to=settings.AUTH_USER_MODEL),
        ),
    ]
