# Generated by Django 6.0.3 on 2026-09-26 09:09

import backupapp.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backupapp', '0005_alter_backupinvitation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backupagent',
            options={'verbose_name': 'Agent backupu (archiwalny)', 'verbose_name_plural': 'Agenci backupu (archiwalni)'},
        ),
        migrations.AlterModelOptions(
            name='backupinvitation',
            options={'ordering': ['user__username'], 'verbose_name': 'Zaproszenie / instalacja aplikacji', 'verbose_name_plural': 'Zaproszenia / instalacje aplikacji'},
        ),
        migrations.AlterField(
            model_name='backupinvitation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
        migrations.CreateModel(
            name='MonitoredApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Główny telefon', max_length=100, verbose_name='Nazwa aplikacji / urządzenia')),
                ('app_type', models.CharField(choices=[('backup_phone', 'Backup telefonu (Termux)'), ('cron_job', 'Cykliczny skrypt / Cron'), ('vps_service', 'Usługa / Serwis VPS'), ('custom_app', 'Inna własna aplikacja / Skrypt')], default='backup_phone', max_length=32, verbose_name='Typ aplikacji')),
                ('token', models.CharField(db_index=True, default=backupapp.models.generate_app_token, max_length=64, unique=True, verbose_name='Token API aplikacji')),
                ('is_active', models.BooleanField(default=True, verbose_name='Czy aktywna')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Ostatni kontakt')),
                ('last_status_code', models.IntegerField(default=0, verbose_name='Ostatni kod wyjścia (0=OK)')),
                ('log', models.TextField(blank=True, default='', verbose_name='Ostatni dziennik (log)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_apps', to=settings.AUTH_USER_MODEL, verbose_name='Właściciel (Użytkownik)')),
            ],
            options={
                'verbose_name': 'Monitorowana Aplikacja / Zadanie',
                'verbose_name_plural': 'Monitorowane Aplikacje / Zadania',
                'ordering': ['user__username', 'name'],
            },
        ),
        migrations.AddField(
            model_name='backupinvitation',
            name='app',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='backupapp.monitoredapp', verbose_name='Aplikacja / Zadanie'),
        ),
    ]
