# Generated by Django 6.0.3 on 2026-09-26 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backupapp', '0006_alter_backupagent_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoredapp',
            name='user',
        ),
        migrations.RemoveField(
            model_name='backupinvitation',
            name='app',
        ),
        migrations.AlterModelOptions(
            name='backupinvitation',
            options={'ordering': ['user__username'], 'verbose_name': 'Zaproszenie do instalacji', 'verbose_name_plural': 'Zaproszenia do instalacji'},
        ),
        migrations.DeleteModel(
            name='BackupAgent',
        ),
        migrations.DeleteModel(
            name='MonitoredApp',
        ),
    ]
