# Generated by Django 6.0.3 on 2026-09-26 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backupapp', '0007_remove_monitoredapp_user_remove_backupinvitation_app_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupinvitation',
            name='token_link',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='Token DRF konta maszynowego'),
        ),
        migrations.AlterField(
            model_name='backupinvitation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Opiekun (człowiek)'),
        ),
    ]
