# Generated by Django 6.0.3 on 2026-04-19 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dziecko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('librus_login', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ogloszenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogloszenie_id', models.CharField(max_length=100)),
                ('dziecko', models.CharField(max_length=200)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('tytul', models.CharField(max_length=255)),
                ('tresc', models.TextField()),
                ('wyslane', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Ogłoszenia',
                'unique_together': {('ogloszenie_id', 'dziecko')},
            },
        ),
        migrations.CreateModel(
            name='Wiadomosc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiadomosc_id', models.CharField(max_length=200)),
                ('librus_data', models.DateTimeField(blank=True, null=True)),
                ('nadawca', models.CharField(blank=True, max_length=200, null=True)),
                ('temat', models.CharField(blank=True, max_length=255, null=True)),
                ('tresc', models.TextField(blank=True, null=True)),
                ('wyslane', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('dziecko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiadomosci', to='librus.dziecko')),
            ],
            options={
                'verbose_name_plural': 'Wiadomości',
                'constraints': [models.UniqueConstraint(fields=('wiadomosc_id', 'dziecko'), name='unique_wiadomosc_per_dziecko')],
            },
        ),
    ]
