# Generated by Django 6.0.3 on 2026-04-19 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dziecko',
            options={'verbose_name_plural': 'Dzieci'},
        ),
        migrations.RenameField(
            model_name='ogloszenie',
            old_name='data',
            new_name='librus_data',
        ),
    ]
