# Generated by Django 6.0.3 on 2026-04-23 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librus', '0003_dziecko_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dziecko',
            name='imie',
        ),
        migrations.RemoveField(
            model_name='dziecko',
            name='nazwisko',
        ),
        migrations.AlterField(
            model_name='dziecko',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
