# Generated by Django 6.0.3 on 2026-04-23 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librus', '0004_remove_dziecko_imie_remove_dziecko_nazwisko_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogloszenie',
            name='nadawca',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ogloszenie',
            name='dziecko',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ogloszenia', to='librus.dziecko'),
        ),
    ]
