# Generated by Django 6.0.3 on 2026-04-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librus', '0005_ogloszenie_nadawca_alter_ogloszenie_dziecko'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ogloszenie',
            unique_together=set(),
        ),
    ]
